'*.{ts,tsx,js}':
  - "eslint --cache --cache-location ./node_modules/.cache/eslintcache --fix "
  - "prettier --log-level warn --cache --write --timeout 30000"
'*.scss':
  - 'stylelint --cache --cache-location ./node_modules/.cache/.stylelintcache'
  - 'prettier --log-level warn --cache --write'
'*.{json}': 'prettier --log-level warn --cache --write'
